# Generated by Django 3.2.5 on 2021-07-27 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=100)),
                ("has_died", models.BooleanField()),
                ("eye_color", models.CharField(max_length=50)),
                ("fruits", models.TextField(null=True)),
                ("vegetables", models.TextField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.company",
                    ),
                ),
                ("friends", models.ManyToManyField(to="api.People")),
            ],
        ),
    ]
